// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Drivetrain;

/**
 *
 */
public class RotateYaw extends CommandBase {
    private final Drivetrain m_drivetrain;
    private final double m_degrees;

    public RotateYaw(Drivetrain drivetrain, double degrees) {
        m_drivetrain = drivetrain;
        m_degrees = degrees;

        addRequirements(m_drivetrain);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_drivetrain.rotateYawBy(Rotation2d.fromDegrees(m_degrees));
    }

    @Override
    public boolean isFinished() {
        return true;
    }
}
