// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Drivetrain;

/**
 *
 */
public class RotateYaw extends CommandBase {
    private final Drivetrain m_drivetrain;
    private final SetYaw m_realCommand;

    public RotateYaw(Drivetrain drivetrain, double degrees) {
        m_drivetrain = drivetrain;
        m_realCommand = new SetYaw(m_drivetrain, m_drivetrain.getYaw().getDegrees() + degrees);

        addRequirements(m_drivetrain);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_realCommand.initialize();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_realCommand.execute();
    }

    @Override
    public void end(boolean interrupted) {
        m_realCommand.end(interrupted);
    }

    @Override
    public boolean isFinished() {
        return m_realCommand.isFinished();
    }
}
